title: Enchiridion
timezone: Australia/Melbourne

register_sw: true

# SEO
tagline: Enchiridion of Epictetus
description: The Enchiridion of Epictetus, an ancient handbook to the philosophy of Stoicism.
locale: en-AU
