name: enchiridion
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+2
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yaml: ^3.1.2
  auto_size_text: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  url_launcher: ^6.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/chapters.yaml
    - assets/translations.yaml
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 19
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true
